DDCE-4866 Add tests for new change role page and navigation
hmrc/advance-valuation-rulings-ui-tests pull request #58
Opened 2024-02-07 14:22 UTC by mywyau

2024-02-14 08:48 UTC, gastonracui requested changes

2024-02-14 08:48 UTC, gastonracui commented on src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/ChangeImporterRoleSteps.scala
> + * Copyright 2023 HM Revenue & Customs
2024...

2024-02-14 08:48 UTC, gastonracui commented on src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/ChangeImporterRoleSteps.scala
> + * Copyright 2023 HM Revenue & Customs
and also check at other files

2024-02-14 08:49 UTC, gastonracui commented
check PR recommendations as well

2024-02-15 11:27 UTC, mywyau commented on src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/ChangeImporterRoleSteps.scala
> + * Copyright 2023 HM Revenue & Customs
done

2024-02-16 10:58 UTC, gastonracui approved these changes

2024-02-16 10:58 UTC, merged